import {Inter} from 'next/font/google';
import './globals.css';
import NavBar from '@/components/navBar';

const inter = Inter({subsets: ['latin']});

export const metadata = {
  title: 'Aesthetic Calculator',
  description: 'Generated by create next app',
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <div className='px-4 pb-4'>
          {children}
        </div>
      </body>
    </html>
  );
}
